# Use the official Nginx base image
FROM nginx

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/

# Expose port 80 for incoming HTTP traffic
# EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]